
spring.application.name=EESOO

server.port=${SERVER_PORT:9090}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s


auth.paseto.local-key-base64=${AUTH_PASETO_LOCAL_KEY_BASE64}
auth.paseto.issuer=${AUTH_PASETO_ISSUER:eesoo}
auth.paseto.access-audience=${AUTH_PASETO_ACCESS_AUDIENCE:eesoo-api}
auth.paseto.refresh-audience=${AUTH_PASETO_REFRESH_AUDIENCE:eesoo-auth-refresh}
auth.paseto.access-token-duration=${AUTH_PASETO_ACCESS_TOKEN_DURATION:15m}

auth.session.duration=${AUTH_SESSION_DURATION:30d}

auth.pin-reset.first-failure-duration=${AUTH_PIN_RESET_FIRST_FAILURE_DURATION:10m}
auth.pin-reset.reset-duration=${AUTH_PIN_RESET_DURATION:15m}

