import React from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';

type Props = {
  username: string;
  onLoginPress: () => void;
};

export default function RegisterSuccessScreen({
  username,
  onLoginPress,
}: Props) {
  return (
    <View className="flex-1 justify-between bg-slate-100 px-5 pb-8 pt-14">
      <View>
        <Text className="text-3xl font-extrabold tracking-tight text-slate-900">
          Account Created
        </Text>

        <Text className="mt-2 text-sm text-slate-600">
          Remember your autogenerated username before logging in.
        </Text>

        <View className="mt-6 rounded-2xl border border-slate-200 bg-white p-4">
          <Text className="mb-2 text-sm font-semibold text-slate-700">
            Username
          </Text>

          <TextInput
            value={username}
            editable={false}
            className="rounded-xl border border-slate-300 bg-slate-100 px-4 py-3 text-base font-semibold text-slate-900"
          />
        </View>
      </View>

      <Pressable
        onPress={onLoginPress}
        className="items-center rounded-xl bg-teal-600 px-4 py-3"
      >
        <Text className="text-base font-bold text-white">Login</Text>
      </Pressable>
    </View>
  );
}